-- اسکریپت بازسازی کامل دیتابیس ربات میانجی (Supabase)
-- هشدار: این اسکریپت تمام جداول قبلی را حذف و از نو می‌سازد.

-- ۰. غیرفعال کردن موقت قیدها (در صورت نیاز - البته DROP CASCADE کافی است)
-- DROP TABLE IF EXISTS commands CASCADE; -- اگر جدولی به این نام وجود داشت

-- ۱. حذف جداول به ترتیب معکوس وابستگی
DROP TABLE IF EXISTS admin_audit_log CASCADE;
DROP TABLE IF EXISTS support_tickets CASCADE;
DROP TABLE IF EXISTS disputes CASCADE;
DROP TABLE IF EXISTS withdrawal_requests CASCADE;
DROP TABLE IF EXISTS pending_receipts CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS commission_logs CASCADE;
DROP TABLE IF EXISTS ambassadors CASCADE;
DROP TABLE IF EXISTS user_states CASCADE;
DROP TABLE IF EXISTS contracts CASCADE;
DROP TABLE IF EXISTS bot_settings CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- ۲. ساخت توابع کمکی
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- ۳. جدول کاربران (Heder Table)
CREATE TABLE users (
    id BIGINT PRIMARY KEY, -- Telegram ID
    username TEXT,
    first_name TEXT,
    full_name TEXT,
    phone_number TEXT,
    wallet_balance NUMERIC DEFAULT 0,
    invited_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    role TEXT DEFAULT 'user', -- user, ambassador, admin, owner
    impersonated_by BIGINT,
    first_name_real TEXT,
    last_name_real TEXT,
    is_verified BOOLEAN DEFAULT FALSE,
    national_id TEXT,
    is_blacklisted BOOLEAN DEFAULT FALSE,
    payment_cards JSONB DEFAULT '[]'::jsonb,
    is_terms_accepted BOOLEAN DEFAULT FALSE,
    terms_accepted_at TIMESTAMP WITH TIME ZONE,
    registration_ip TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ۴. جدول وضعیت کاربران (FSM State)
CREATE TABLE user_states (
    id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    state TEXT,
    data JSONB DEFAULT '{}'::jsonb,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TRIGGER update_user_states_updated_at BEFORE UPDATE ON user_states 
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- ۵. جدول سفیران (Ambassadors)
CREATE TABLE ambassadors (
    telegram_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    commission_rate NUMERIC DEFAULT 30.0,
    total_referrals INTEGER DEFAULT 0,
    total_earnings NUMERIC DEFAULT 0,
    withdrawable_balance NUMERIC DEFAULT 0,
    tier_level TEXT DEFAULT 'Bronze',
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ۶. جدول معاملات (Contracts / Escrow)
CREATE TABLE contracts (
    id TEXT PRIMARY KEY, -- UID داخلی (مثلا uuid)
    contract_id TEXT UNIQUE, -- شناسه نمایشی (مثلا DEV-123)
    title TEXT,
    amount NUMERIC,
    description TEXT,
    deadline INTEGER, -- تعداد روز
    category TEXT, -- DEV, DS, CNT, ...
    status TEXT DEFAULT 'waiting_signature',
    buyer_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    seller_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    creator_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    staged_payment BOOLEAN DEFAULT FALSE,
    milestones JSONB DEFAULT '[]'::jsonb,
    history JSONB DEFAULT '[]'::jsonb,
    delivery_files JSONB DEFAULT '[]'::jsonb,
    receipt_file_id TEXT,
    payment_verified BOOLEAN DEFAULT FALSE,
    late_penalty_per_day NUMERIC DEFAULT 0,
    delivery_deadline TIMESTAMP WITH TIME ZONE,
    recurring BOOLEAN DEFAULT FALSE,
    free_edits_total INTEGER DEFAULT 3,
    free_edits_left INTEGER DEFAULT 3,
    buyer_otp_verified BOOLEAN DEFAULT FALSE,
    seller_otp_verified BOOLEAN DEFAULT FALSE,
    buyer_signed_at TIMESTAMP WITH TIME ZONE,
    seller_signed_at TIMESTAMP WITH TIME ZONE,
    buyer_otp_code TEXT,
    seller_otp_code TEXT,
    buyer_fullname TEXT,
    seller_fullname TEXT,
    buyer_national_id TEXT,
    seller_national_id TEXT,
    buyer_phone TEXT,
    seller_phone TEXT,
    buyer_alt_phone TEXT,
    seller_alt_phone TEXT,
    paid_at TIMESTAMP WITH TIME ZONE,
    delivered_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    signed_by_second_party BOOLEAN DEFAULT FALSE,
    project_file_id TEXT,
    created_by_admin BOOLEAN DEFAULT FALSE,
    dispute_reason TEXT,
    dispute_opened_by BIGINT,
    cancel_requested_by BIGINT,
    dispute_room_link TEXT,
    dispute_verdict TEXT,
    negotiation_text TEXT,
    commission_payer TEXT DEFAULT 'freelancer',
    negotiation_count INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TRIGGER update_contracts_updated_at BEFORE UPDATE ON contracts 
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- ۷. جدول تراکنش‌ها (Wallet Transactions)
CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    amount NUMERIC,
    type TEXT, -- deposit, withdrawal, commission, payment, refund, penalty
    status TEXT DEFAULT 'completed',
    description TEXT,
    receipt_file_id TEXT,
    admin_document_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ۸. جدول پورسانت‌ها (Ambassador Commissions)
CREATE TABLE commission_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ambassador_id BIGINT REFERENCES ambassadors(telegram_id) ON DELETE CASCADE,
    trade_id TEXT REFERENCES contracts(contract_id) ON DELETE SET NULL,
    trade_amount NUMERIC,
    platform_fee NUMERIC,
    ambassador_share NUMERIC,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ۹. جدول فیش‌های در انتظار بررسی (Pending Receipts)
CREATE TABLE pending_receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT, -- deposit, contract_payment
    related_id TEXT, -- contract_id یا null
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    file_id TEXT,
    amount NUMERIC,
    description TEXT,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TRIGGER update_pending_receipts_updated_at BEFORE UPDATE ON pending_receipts 
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- ۱۰. جدول درخواست‌های برداشت (Withdrawal Requests)
CREATE TABLE withdrawal_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    amount NUMERIC,
    sheba TEXT,
    sheba_or_card TEXT,
    holder_name TEXT,
    type TEXT DEFAULT 'standard',
    status TEXT DEFAULT 'pending',
    suspicious_flag BOOLEAN DEFAULT FALSE,
    resolved_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    documents JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TRIGGER update_withdrawal_requests_updated_at BEFORE UPDATE ON withdrawal_requests 
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- ۱۱. جدول پرونده‌های داوری (Disputes)
CREATE TABLE disputes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id TEXT REFERENCES contracts(contract_id) ON DELETE CASCADE,
    opened_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    reason TEXT,
    proof_file_id TEXT,
    verdict TEXT,
    split_ratio_freelancer NUMERIC,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ۱۲. جدول تیکت‌های پشتیبانی (Support Tickets)
CREATE TABLE support_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    subject TEXT,
    detail TEXT,
    status TEXT DEFAULT 'open',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ۱۳. جدول تنظیمات سیستمی (Bot Settings)
CREATE TABLE bot_settings (
    key TEXT PRIMARY KEY,
    value JSONB,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TRIGGER update_bot_settings_updated_at BEFORE UPDATE ON bot_settings 
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- ۱۴. جدول لاگ فعالیت ادمین‌ها (Audit Log)
CREATE TABLE admin_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    action TEXT,
    detail TEXT,
    target_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ۱۵. ایندکس‌ها برای بهینه‌سازی
CREATE INDEX idx_users_username ON users(username);
CREATE INDEX idx_users_phone ON users(phone_number);
CREATE INDEX idx_contracts_buyer ON contracts(buyer_id);
CREATE INDEX idx_contracts_seller ON contracts(seller_id);
CREATE INDEX idx_contracts_status ON contracts(status);
CREATE INDEX idx_transactions_user ON transactions(user_id);
CREATE INDEX idx_pending_receipts_user ON pending_receipts(user_id);
CREATE INDEX idx_withdrawal_status ON withdrawal_requests(status);
CREATE INDEX idx_disputes_contract ON disputes(transaction_id);

-- پایان اسکریپت
